[package]
name = "hotaru_trans"
version = "0.8.0"
edition = "2024"
authors = ["Redstone <redstone@fds.moe>"]
description = "Procedural macros for Hotaru framework"
license = "GPL-3.0"
repository = "https://github.com/Field-of-Dreams-Studio/hotaru"
categories = ["network-programming", "web-programming::http-server"]
keywords = ["hotaru", "macros"]

[dependencies]
hotaru_meta = { version = "0.8.0", path = "../hotaru_meta" }
ctor = { version = "0.4.0", optional = true }

[features]
default = []
external-ctor = ["ctor"]

[lib]
proc-macro = true
