[package]
name = "hotaru_core"
version = "0.8.0"
edition = "2024"
authors = ["Redstone <redstone@fds.moe>"] 
description = "Small, sweet, easy framework for full-stack web application" 
license = "GPL-3.0" 
repository = "https://github.com/Field-of-Dreams-Studio/hotaru" 
categories = ["network-programming", "web-programming::http-server"] 
keywords = ["hotaru"]

[dependencies]
akari = { version = "0.2.6", features = ["full"] }
tokio = { version = "1.28", features = ["full"] }
parking_lot = "0.12"

hotaru_lib = { version = "0.7.2", path = "../hotaru_lib" , features = ["url_encoding", "compression"] }  
regex = "1.5.6" 
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2.0"
rustls-platform-verifier = { version = "0.6.0", default-features = false }
webpki-roots = "1"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
tokio-util = { version = "0.7", features = ["codec"] }
include_dir = "0.7" 
bytes = "1"
http = "1"
fnv = "1.0"
once_cell = "1.17" 
async-trait = "0.1.88"
tracing = "0.1"
[dev-dependencies]
hex = "0.4"
serde_json = "1.0"
rand = "0.8"
quickcheck = "1.0"
env_logger = "0.10"

[features] 
default = [] 

dev-log = [] # Feature for debugging hotaru 
