[package]
name = "example_hotaru"
version = "0.1.0"
edition = "2024" 
build = "build.rs" 

[dependencies]
hotaru = { path = "../hotaru", features = ["trans"] }
ctor = "0.4.0"
once_cell = "1.17"
tokio = { version = "1", features = ["full"] }
