[package]
name = "multi_protocol_example"
version = "0.1.0"
edition = "2024" 
build = "build.rs" 

[dependencies]
hotaru = { version = "0.7.0", path = "../hotaru" } 
htmstd = { path = "../htmstd" } 
ctor = "0.4.0"
once_cell = "1.17"
tokio = { version = "1", features = ["full"] }
